name: Manual Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  manual-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ runner.os }}-${{ hashFiles('app/*.txt') }}

      - uses: isort/isort-action@master
        with:
          requirementsFiles: "app/requirements.txt app/dev.txt"
          configuration: "--check-only --diff"
