name: Manual Workflow

on:
  pull_request:
    branches:
      - sp_test

jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Get PR information
      run: |
        PR_NUMBER=${{ github.event.number }}
        NEW_DESCRIPTION="Your updated PR description here"
        echo "SP PR Number: $PR_NUMBER"

        API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}"

        # Update the description
        curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"body\": \"$NEW_DESCRIPTION\"}" \
          $API_URL
        echo "PR description updated."
