name: Manual Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Get PR information
      run: |
        PR_NUMBER=${{ github.event.number }}
        PR_TITLE=${{ github.event.title }}
        EVENT=${{ github.event }}
        NEW_DESCRIPTION="Your updated PR description here"
        echo "PR Number: $PR_NUMBER"
        echo "EVENT : $EVENT"
        echo "PR_TITLE : $PR_TITLE"

        API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}"
        pr_base_branch=${{ github.base_ref }}
        pr_head_branch=${{ github.head_ref }}
        ref_name=${{ github.ref }}
        echo "Base Branch: $pr_base_branch"
        echo "Head Branch: $pr_head_branch"
        echo "ref Name: $ref_name"

        # Update the description
        curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"body\": \"$NEW_DESCRIPTION\"}" \
          $API_URL
        echo "PR description updated."
